# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoupChef' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoupChef
  
  # Adding Whatfix dependency
  pod 'WhatFix', '~> 1.0.3'

end
